// <auto-generated />
using LocalBandsList.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LocalBandsList.Migrations
{
  [DbContext(typeof(LocalBandsListContext))]
  [Migration("20200612161502_Second")]
  partial class Second
  {
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder
          .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
          .HasAnnotation("Relational:MaxIdentifierLength", 64);

      modelBuilder.Entity("LocalBandsList.Models.Band", b =>
          {
            b.Property<int>("BandId")
                      .ValueGeneratedOnAdd();

            b.Property<string>("Description")
                      .HasMaxLength(300);

            b.Property<string>("Name")
                      .IsRequired()
                      .HasMaxLength(50);

            b.Property<string>("PhoneNumber");

            b.Property<string>("Type")
                      .IsRequired();

            b.Property<int>("UserId");

            b.Property<string>("WebSite");

            b.HasKey("BandId");

            b.ToTable("Bands");
          });
#pragma warning restore 612, 618
    }
  }
}
